### ISSUE TITLE
tests don't pass on master

### ISSUE THREAD

**Issue by rogpeppe** [frankban/quicktest#11]
I get these failures when running tests on master (commit 5af72c38d1adb886d1c666d1c61f30a2efb78028):

	--- FAIL: TestCheckers (0.01s)
	    --- FAIL: TestCheckers/CmpEquals:_different_values (0.00s)
	    	quicktest_test.go:214: prefix:
	    		got  "\nvalues are not equal:\n(-got +want)\nroot.Ints[1->?]:\n\t-: 47\n\t+: <non-existent>\nchecker_test.go:561:\n        558       t.Run(test.about, func(t *testing.T) {\n        559         tt := &testingT{}\n        560         c := qt.New(tt)\n        561!        ok := c.Check(test.got, test.checker, test.args...)\n        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)\n        563       })\n        564       t.Run(\"Not \"+test.about, func(t *testing.T) {\n"
	    		want "\nvalues are not equal:\n(-got +want)\nroot.Ints:\n\t-: []int{42, 47}\n\t+: []int{42}\n":
	    		-----------------------------------
	    		
	    		values are not equal:
	    		(-got +want)
	    		root.Ints[1->?]:
	    			-: 47
	    			+: <non-existent>
	    		checker_test.go:561:
	    		        558       t.Run(test.about, func(t *testing.T) {
	    		        559         tt := &testingT{}
	    		        560         c := qt.New(tt)
	    		        561!        ok := c.Check(test.got, test.checker, test.args...)
	    		        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)
	    		        563       })
	    		        564       t.Run("Not "+test.about, func(t *testing.T) {
	    --- FAIL: TestCheckers/CmpEquals:_different_values_with_options (0.00s)
	    	quicktest_test.go:214: prefix:
	    		got  "\nvalues are not equal:\n(-got +want)\nSort({[]int}).([]int)[2]:\n\t-: 4\n\t+: 3\nchecker_test.go:561:\n        558       t.Run(test.about, func(t *testing.T) {\n        559         tt := &testingT{}\n        560         c := qt.New(tt)\n        561!        ok := c.Check(test.got, test.checker, test.args...)\n        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)\n        563       })\n        564       t.Run(\"Not \"+test.about, func(t *testing.T) {\n"
	    		want "\nvalues are not equal:\n(-got +want)\nSort({[]int})[2]:\n\t-: 4\n\t+: 3\n":
	    		-----------------------------------
	    		
	    		values are not equal:
	    		(-got +want)
	    		Sort({[]int}).([]int)[2]:
	    			-: 4
	    			+: 3
	    		checker_test.go:561:
	    		        558       t.Run(test.about, func(t *testing.T) {
	    		        559         tt := &testingT{}
	    		        560         c := qt.New(tt)
	    		        561!        ok := c.Check(test.got, test.checker, test.args...)
	    		        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)
	    		        563       })
	    		        564       t.Run("Not "+test.about, func(t *testing.T) {
	    --- FAIL: TestCheckers/DeepEquals:_different_values (0.00s)
	    	quicktest_test.go:214: prefix:
	    		got  "\nvalues are not equal:\n(-got +want)\n{[]int}[0]:\n\t-: 1\n\t+: 3\n{[]int}[2]:\n\t-: 3\n\t+: 1\nchecker_test.go:561:\n        558       t.Run(test.about, func(t *testing.T) {\n        559         tt := &testingT{}\n        560         c := qt.New(tt)\n        561!        ok := c.Check(test.got, test.checker, test.args...)\n        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)\n        563       })\n        564       t.Run(\"Not \"+test.about, func(t *testing.T) {\n"
	    		want "\nvalues are not equal:\n(-got +want)\n{[]int}:\n\t-: []int{1, 2, 3}\n\t+: []int{3, 2, 1}\n":
	    		-----------------------------------
	    		
	    		values are not equal:
	    		(-got +want)
	    		{[]int}[0]:
	    			-: 1
	    			+: 3
	    		{[]int}[2]:
	    			-: 3
	    			+: 1
	    		checker_test.go:561:
	    		        558       t.Run(test.about, func(t *testing.T) {
	    		        559         tt := &testingT{}
	    		        560         c := qt.New(tt)
	    		        561!        ok := c.Check(test.got, test.checker, test.args...)
	    		        562         checkResult(t, ok, tt.errorString(), test.expectedCheckFailure)
	    		        563       })
	    		        564       t.Run("Not "+test.about, func(t *testing.T) {
	FAIL
	exit status 1
	FAIL	github.com/frankban/quicktest	0.014s

**Comment by frankban** [comment]
This was a dependency issue.
