### ISSUE TITLE
LGPL license in checker.go

### ISSUE THREAD

**Issue by Will2728** [frankban/quicktest#151]
You reference an LGPLv3 license in **checker.go**, doesn't that mean that anyone using this code is required to follow that license if using your code?  The code in question seems very simple, why not rewrite it to avoid the licensing issues that will surely result from using this code?

func (c *satisfiesChecker) Check(got interface{}, args []interface{}, note func(key string, value interface{})) (err error) {
	// Original code at
	// <https://github.com/juju/testing/blob/master/checkers/bool.go>.
	// Copyright 2011 Canonical Ltd.
	// Licensed under the LGPLv3, see LICENSE file for details.

Note that there is nothing in the LICENSE file about an LGPL license being in effect?

**Comment by frankban** [comment]
The code is already pretty much different from the original.
I think I'll keep the link as a reference to the original implementation, but drop the license info.

**Comment by frankban** [comment]
Released as v1.14.5
