### ISSUE TITLE
Question: working with go-cmp.Options

### ISSUE THREAD

**Issue by dnephin** [frankban/quicktest#22]
Hello, I was just looking around [cmp importers](https://godoc.org/github.com/google/go-cmp/cmp?importers) to see who else was using `go-cmp` and how they were working with `go-cmp` and I found this project.

It seems to have some similarities with the [`gotestyourself`](https://github.com/gotestyourself/gotestyourself) project I have been working on. (`C.Mkdir` -> [fs.NewDir()](https://godoc.org/github.com/gotestyourself/gotestyourself/fs), `Assert/Check` -> [Assert/Check](https://godoc.org/github.com/gotestyourself/gotestyourself/assert#Assert), `C.Setenv` -> [env.Patch()](https://godoc.org/github.com/gotestyourself/gotestyourself/env#Patch)). 

The big differences seem to be
1) `quicktest` has a focus on "lifecycle" (`AddCleanup`/`Cleanup`) which is not something that I've looked at. I considered a [gotestyourself/suite](https://github.com/dnephin/gotestyourself/commit/79f0b3fdb8b903064142b1318850fd08e8b511e1) that could be used as a drop in replacement of `testify/suite` to facilitate [automated migration from testify](https://github.com/gotestyourself/gotestyourself/pull/36), but I wasn't sure if it was worth adding something that was basically just a copy of the testify design. I really like the idea of `C.Run()` to automatically run `AddCleanup`.
2) `quicktest` assertions seem to be modeled after [gocheck](https://godoc.org/gopkg.in/check.v1#Checker), where as `gotestyourself` uses a [Comparison](https://godoc.org/github.com/gotestyourself/gotestyourself/assert/cmp#Comparison) type which is responsible for formatting the error message. Convenience functions are added to make the `assert` package similar to `testify/require` (with hopefully less interface bloat and more idiomatic naming).

So my questions:
1) How have you found adoption of this package? Is it used internally in some projects or is it still being developed?
2) What's your experience with creating `go-cmp` `Option`? AllowUnexported and IgnoreUnexported are pretty straightfoward. The other case I've found  for them is to compare `time.Time` or `time.Duration` values that use `time.Now()`. For those cases I'm thinking of making a [more convenient interface](https://github.com/gotestyourself/gotestyourself/pull/62/files) ([example](https://github.com/gotestyourself/gotestyourself/pull/62/files#diff-2e25030b521eef3c20d0f17cb1ad5f0cR18)) but I'm not sure if I'm missing something that would make that interface unnecessary.

**Comment by rogpeppe** [comment]
We're still developing quicktest, so we're not focusing on wide adoption yet, although we're successfully converting many of our projects to use it. I'm quite happy with the balance of power and simplicity that it provides, and how it integrates nicely with the standard library testing.

Areas for future work are producing better output on errors. The public API is now stable and won't change in a backwardly incompatible way.

**Comment by rogpeppe** [comment]
As for the cmp package, it's excellent. The API is nice and it's good that it fails on comparison of unexported fields by default. I'm less sure about the use of github.com/kr/pretty for value output, but we'll see.
