### ISSUE TITLE
Comparing uninitialized maps to nil

### ISSUE THREAD

**Issue by akyoto** [frankban/quicktest#45]
This looks like a bug:

```go
var shouldBeNil map[string]interface{}

if shouldBeNil == nil {
	c.Log("Indeed nil, according to Go")
}

c.Assert(shouldBeNil, qt.Equals, nil)
```

It generates:

```text
Indeed nil, according to Go

       error:
          values are not equal
        got:
          map[string]interface {}{}
        want:
          nil
```

**Comment by akyoto** [comment]
Nevermind, I should have taken a look at `qt.IsNil`.

However, does this still look like something you'd want to address or is this behaviour "by design"?
If it is, feel free to close.

**Comment by frankban** [comment]
Yes it is by design, see [0]. This way it is possible to check that something is actually nil or use IsNil for a less strict check.
[0] https://github.com/frankban/quicktest/blob/master/checker.go#L44

**Comment by akyoto** [comment]
I see, so that's why both are needed. A strict and a less strict version.
Thank you for the clarification @frankban!
