### ISSUE TITLE
More practical diff output

### ISSUE THREAD

**Issue by bep** [frankban/quicktest#61]
Currently, I may get something like this:

```bash
 quicktest.go:306: 
        error:
          values are not deep equal
        diff (-got +want):
            []string{
          - 	"a/b/c/f-1.txt",
          - 	"a/b/c/f-2.txt",
          - 	"a/b/c/f-3.txt",
          - 	"cf2/myfile.txt",
            }
        stack:
          /Users/bep/dev/go/gohugoio/hugo/hugofs/rootmapping_fs_test.go:397
            c.Assert(all, qt.DeepEquals, []string{})
```

Assertion errors like the above happen, in my experience, almost always only when you're creating the test itself:

1. Add some dummy assertion value.
2. Run the test and see that it fails.
3. If the values printed are correct, put them in there and re-run the test.

Given the above, it would be much more useful to (also) have something like `fmt.Printf("%#v", values)` in the output so I could copy and paste it.

**Comment by frankban** [comment]
This is achievable by running the same test with verbosity (`go test -v`), in which case DeepEquals also outputs the actual values. Is that sufficient for the use case you described?

**Comment by bep** [comment]
>Is that sufficient for the use case you described?

Yes. I probably didn't think this through for big object graphs, which can get very verbose ...
