### ISSUE TITLE
use testing.T.Helper to avoid reporting quicktest.go filenames

### ISSUE THREAD

**Issue by mvdan** [frankban/quicktest#80]
https://play.golang.org/p/T7QxpYdwfhg

All failures start with `quicktest.go:348:`, which is kind of useless. The quicktest APIs should use `t.Helper` so that the filename reported in the testing package is for the user's code.

As a follow-up, the stack trace should then *not* include that filename and line number, because it would be redundant. If the stack trace is just that one position, I think it should be omitted.

**Comment by rogpeppe** [comment]
> As a follow-up, the stack trace should then not include that filename and line number, because it would be redundant. If the stack trace is just that one position, I think it should be omitted.

I disagree. It's not redundant because the stack trace also includes the literal source code for the statement that failed - it's not just a file location.

**Comment by mvdan** [comment]
That makes sense. I just wasn't noticing how nice stack traces can be, because I wasn't seeing them at all due to #79 :)

**Comment by mvdan** [comment]
I should also note that this will mean requiring Go 1.9 or later, unless we do an interface check. I think requiring 1.9 should be fine, as it came out over three years ago and hasn't even had any sort of update for nearly two years now.

**Comment by frankban** [comment]
I also agree that requiring 1.9 is fine.

**Comment by frankban** [comment]
This is now released as `v1.11.1`.
