### ISSUE TITLE
quicktest\quicktest.go:22: t.Helper undefined (type testing.TB has no field or method Helper)

### ISSUE THREAD

**Issue by jiadsii** [frankban/quicktest#89]
when you  go get github.com/frankban/quicktest
it wrong,it need method Helper

**Comment by frankban** [comment]
The testing.TB.Helper method has been introduced in Go 1.9, while quicktest is tested for working starting from Go 1.11.
Which Go version are you using? Do you have the ability to update to a more recent version, supported by quicktest?

**Comment by frankban** [comment]
Closing this. Feel free to reopen if this was not related to the used Go version.
