### ISSUE TITLE
name the package qt?

### ISSUE THREAD

**Issue by mvdan** [frankban/quicktest#90]
I was just thinking that the package layout in this module is a bit weird. I understand that we want the uses of the API to be short, so `qt.Assert` is nicer than `quicktest.Assert`. I also get that a module/repo path like github.com/frankban/qt would be a bit confusing.

That said, I think it's a bit unfortunate that we don't just publish the API under a `package qt`. This would be tricky to do in v1 without duplicating the entire API, but for v2 we could perhaps use something like `github.com/frankban/quicktest/v2/qt`. The import gets a tiny bit longer, but we avoid having to name the import. Plus, other tools like `goimports` and `pkg.go.dev` will work much better, as there will no longer be a mismatch between the actual package name and how it's used in code.

**Comment by rogpeppe** [comment]
For v2, the plan is to move to `github.com/go-quicktest/qt`.

**Comment by mvdan** [comment]
Ah, great :)

**Comment by toffaletti** [comment]
Has anyone floated a proposal to integrate `Checker` into the stdlib `testing` package? It really feels like it belongs there.

**Comment by mvdan** [comment]
https://github.com/go-quicktest/qt has been public for some time, but it's not quite ready yet - there is no stable version, for example. It's up to Roger and Francesco.

**Comment by frankban** [comment]
Closing for grouping all the `qt` related considerations at https://github.com/go-quicktest/qt/issues/7
